### ISSUE TITLE
Doubts when implementing the contracts/WalletFactory.sol

### ISSUE THREAD

**Issue by marcelosilva78** [BitGo/eth-multisig-v4#54]
Hi,

I'm trying to deploy wallet eth-multisig-v4 using HardHat as a deployment environment and I'm having problems deploying WalletFactory.sol.

My hardhat-config.js:
```
/**
 * @type import('hardhat/config').HardhatUserConfig
 */

require("@nomiclabs/hardhat-truffle5");
require("@nomiclabs/hardhat-web3");
require("@nomiclabs/hardhat-ethers");

module.exports = {
  solidity: "0.8.10",
};
```

My deploy script to WalletSimple.sol (deploy.js) is:
```
// scripts/deploy.js
async function main () {
  // We get the contract to deploy
  const WalletSimple = await ethers.getContractFactory('WalletSimple');
  console.log('Deploying WalletSimple...');
  const walletsimple = await WalletSimple.deploy();
  await walletsimple.deployed();
  console.log('WalletSimple deployed to:', walletsimple.address);
}

main()
  .then(() => process.exit(0))
  .catch(error => {
    console.error(error);
    process.exit(1);
  });
```

My WalletSimple deployment output:
```
Compilation finished successfully
Deploying WalletSimple...
WalletSimple deployed to: 0x5FbDB2315678afecb367f032d93F642f64180aa3

```
Now I want to deploy the WalletFactory.sol and in README.MD has an info that I must use the "contract address" generated by WalletSimple.sol as a parameter for the _implementationAddress on WalletFactory.sol. I'm not able to pass this address as a parameter to this function in this contract. How do I do that? I've tried it in several ways:

```
constructor(address _implementationAddress(0x5fbdb2315678afecb367f032d93f642f64180aa3)) {
    implementationAddress = _implementationAddress;
  }


  constructor(address _implementationAddress(address(0x5fbdb2315678afecb367f032d93f642f64180aa3))) {
    implementationAddress = _implementationAddress;
  }


  constructor(address _implementationAddress, address 0x5fbdb2315678afecb367f032d93f642f64180aa3) {
    implementationAddress = _implementationAddress;
  }
```

My deployment output:
```
 ~/o/N/w/hardhat  npx hardhat run --network localhost scripts/walletfactory.js                                     4019ms  Qua  5 Jan 20:16:37 2022
Deploying WalletFactory...
Error: missing argument:  in Contract constructor (count=0, expectedCount=1, code=MISSING_ARGUMENT, version=contracts/5.5.0)
    at Logger.makeError (/Users/marcelosilva/ownCloud/NodeProjects/wallet/hardhat/node_modules/@ethersproject/logger/src.ts/index.ts:225:28)
    at Logger.throwError (/Users/marcelosilva/ownCloud/NodeProjects/wallet/hardhat/node_modules/@ethersproject/logger/src.ts/index.ts:237:20)
    at Logger.checkArgumentCount (/Users/marcelosilva/ownCloud/NodeProjects/wallet/hardhat/node_modules/@ethersproject/logger/src.ts/index.ts:296:18)
    at ContractFactory.<anonymous> (/Users/marcelosilva/ownCloud/NodeProjects/wallet/hardhat/node_modules/@ethersproject/contracts/src.ts/index.ts:1227:16)
    at step (/Users/marcelosilva/ownCloud/NodeProjects/wallet/hardhat/node_modules/@ethersproject/contracts/lib/index.js:48:23)
    at Object.next (/Users/marcelosilva/ownCloud/NodeProjects/wallet/hardhat/node_modules/@ethersproject/contracts/lib/index.js:29:53)
    at /Users/marcelosilva/ownCloud/NodeProjects/wallet/hardhat/node_modules/@ethersproject/contracts/lib/index.js:23:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/marcelosilva/ownCloud/NodeProjects/wallet/hardhat/node_modules/@ethersproject/contracts/lib/index.js:19:12)
    at ContractFactory.deploy (/Users/marcelosilva/ownCloud/NodeProjects/wallet/hardhat/node_modules/@ethersproject/contracts/lib/index.js:1132:16) {
  reason: 'missing argument:  in Contract constructor',
  code: 'MISSING_ARGUMENT',
  count: 0,
  expectedCount: 1
}
```

I'm not very familiar with smartcontracts. I would be grateful if anyone could help me with this.

regards

Marcelo

**Comment by diadal** [comment]
npx hardhat run --network localhost scripts/walletfactory.js  missing the constructor it should be

 npx hardhat run --network localhost scripts/walletfactory.js  0x5fbdb2315678afecb367f032d93f642f64180aa3
